# SPDX-License-Identifier: MIT
"""Verify SRI integrity attributes on CDN resources in frontend HTML files."""

import re
from pathlib import Path

FRONTEND_DIR = Path("packages/undef-terminal/src/undef/terminal/frontend")
CF_FRONTEND_DIR = Path("packages/undef-terminal-cloudflare/python_modules/undef/terminal/frontend")
DEMO_DIR = Path("demo")

_JSDELIVR = r"<(?:script|link)[^>]+cdn\.jsdelivr\.net[^>]+>"


def _check_sri(tags: list[str], source: str) -> None:
    for tag in tags:
        assert 'integrity="sha384-' in tag, f"Missing SRI integrity in {source}: {tag}"
        assert 'crossorigin="anonymous"' in tag, f"Missing crossorigin in {source}: {tag}"


# ── build-output copies (gitignored, generated by npm run build:frontend) ───


def test_terminal_html_scripts_have_integrity() -> None:
    html = (FRONTEND_DIR / "terminal.html").read_text()
    scripts = re.findall(r"<script[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert scripts, "Expected CDN script tags in terminal.html"
    _check_sri(scripts, "terminal.html")


def test_terminal_html_stylesheets_have_integrity() -> None:
    html = (FRONTEND_DIR / "terminal.html").read_text()
    links = re.findall(r"<link[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert links, "Expected CDN stylesheet link tags in terminal.html"
    _check_sri(links, "terminal.html")


def test_terminal_html_google_fonts_no_integrity() -> None:
    html = (FRONTEND_DIR / "terminal.html").read_text()
    fonts_links = re.findall(r"<link[^>]+fonts\.googleapis\.com[^>]+>", html)
    for tag in fonts_links:
        assert "integrity=" not in tag, f"Google Fonts should not have SRI: {tag}"


def test_hijack_html_scripts_have_integrity() -> None:
    html = (FRONTEND_DIR / "hijack.html").read_text()
    scripts = re.findall(r"<script[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert scripts, "Expected CDN script tags in hijack.html"
    _check_sri(scripts, "hijack.html")


def test_hijack_html_stylesheets_have_integrity() -> None:
    html = (FRONTEND_DIR / "hijack.html").read_text()
    links = re.findall(r"<link[^>]+cdn\.jsdelivr\.net[^>]+>", html)
    assert links, "Expected CDN stylesheet link tags in hijack.html"
    _check_sri(links, "hijack.html")


def test_hijack_html_google_fonts_no_integrity() -> None:
    html = (FRONTEND_DIR / "hijack.html").read_text()
    fonts_links = re.findall(r"<link[^>]+fonts\.googleapis\.com[^>]+>", html)
    for tag in fonts_links:
        assert "integrity=" not in tag, f"Google Fonts should not have SRI: {tag}"


# ── CF vendored copies (tracked in git, must stay in sync) ──────────────────


def test_cf_terminal_html_cdn_tags_have_integrity() -> None:
    html = (CF_FRONTEND_DIR / "terminal.html").read_text()
    tags = re.findall(_JSDELIVR, html)
    assert tags, "Expected CDN tags in CF python_modules terminal.html"
    _check_sri(tags, "CF terminal.html")


def test_cf_hijack_html_cdn_tags_have_integrity() -> None:
    html = (CF_FRONTEND_DIR / "hijack.html").read_text()
    tags = re.findall(_JSDELIVR, html)
    assert tags, "Expected CDN tags in CF python_modules hijack.html"
    _check_sri(tags, "CF hijack.html")


# ── demo viewer (tracked in git, older xterm version) ───────────────────────


def test_demo_terminal_html_cdn_tags_have_integrity() -> None:
    html = (DEMO_DIR / "terminal.html").read_text()
    tags = re.findall(_JSDELIVR, html)
    assert tags, "Expected CDN tags in demo/terminal.html"
    _check_sri(tags, "demo/terminal.html")
